[book]
authors = ["lzzsG"]
language = "zh"
multilingual = false
description = "Rustlings Notebook Rustlings 系列笔记 通过一系列练习来帮助您熟悉 Rust 语言。从基本的变量、函数、控制结构到更高级的概念如泛型、特征和生命周期管理，涵盖了常见的编程概念和高级主题，如模块、向量、字符串处理和错误处理，智能指针、多线程处理、宏和更多，旨在全面提升您的系统编程能力，每个模块都设计有针对性的练习。"
src = "src"
title = "Rustlings Notebook"


[output.html]
site-url = "/rustlings-notebook/"
default-theme = "black"
preferred-dark-theme = "black"
git-repository-url = "https://github.com/lzzsG/rustlings-notebook"
git-repository-icon = "fa-github"


[output.html.playground]
editable = true
line-numbers  = true